### ISSUE TITLE
ADB extension not detected (sometimes)

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#1242]
**Describe the issue**

When `adb` extension opened, sometimes `adb` is not being detected even though `adb` is installed and path is set

(Needs investigation)

**Comment by fur-gan** [comment]
Error most likely related to this:
```
[2021-09-17T10:00:19.771Z][SidebarAppAdbLogcatComponent][ERROR]: Failed to detect devices due error: * daemon not running; starting now at tcp:5037
* daemon started successfully
```

**Comment by DmitryAstafyev** [comment]
@fur-gan it happens because adb doesn't run daemon with os. daemon will be running with the first call of adb (in the scope on new OS session).
Well it's easy to reproduce:
1. restart PC
2. open chipmunk and open adb
or
deamon can be turn off manulaly. I think in windows it can be done via task manager

Well all we need, just verify is adb deamon is running or not, before starting to work with it
