### ISSUE TITLE
Setting color for Foreground in Filter Details

### ISSUE THREAD

**Issue by liquidchair** [esrlabs/chipmunk#1295]
**Prerequisites**

affected version: 2.22.9

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

The color of the foreground of the filter in logs could be only black or white, even if in the search menu it shows the other one. Found this behavior in .log format files. 

[Side Issue]: 
Also not really understood the logic when the change color of the foreground may also change the color of the background and vice versa. 

**Steps to Reproduce**

1. Choose the color of the foreground different from black or white for the filter in the search menu.
2. The chosen color would be shown in the search menu however, it would be black or white in the log view window.

Chosen colors in search menu:
![colorinsearch1](https://user-images.githubusercontent.com/49911348/143782983-95368b81-1280-42fe-bd6a-5e958e67b0e3.png)
![2021-11-28 21_28_08-Chipmunk](https://user-images.githubusercontent.com/49911348/143782985-3f4c0244-7005-4c57-9064-865514ee6cd2.png)

How it is actually looking in the log window:
![colorinlog](https://user-images.githubusercontent.com/49911348/143782937-aa6b73ab-2d41-446d-9c69-471c18f595df.png)

[Side Issue]: 
1. Choose the color of the background or foreground for the filter in the search menu.
2. Choose the color of the opposite part(background or foreground).

In most cases, it would change the original color from step 1.

**Environment**

Version: 2.22.9
Platform: win32(x64) / Windows_NT / 10.0.19043
Electron: 10.2.0
Electron Rebuild: 2.3.4
ToolKit: 1.4.1
IPC: 0.0.51
Chipmunk Material: 1.2.18
Angular: 12.2.10
Angular Material: 12.2.10

**Comment by DmitryAstafyev** [comment]
Hello, @liquidchair
Thanks for your issue. I will try to describe all step by step.

> The color of the foreground of the filter in logs could be only black or white, even if in the search menu it shows the other one.

In case if user selects `background` (default option) chipmunk **always** selects between black/white most suitable (contrast) color. 

> even if in the search menu it shows the other one

It might be because to highlight an exact match chipmunk always apply black/white model;
On the screenshot below you can see a match for filter `539`. As you can see there are defined and background and foreground colors. But an exact match (word `539`) rendered in black/white mode in any way. We've found this solution as most usable. Background of match calculates automatically based on filter's background, but foreground always b/w. 

![Screenshot from 2021-12-20 09-49-49](https://user-images.githubusercontent.com/12843747/146739213-744155a7-2535-41a5-a9a5-08036e0909f7.png)

>Also not really understood the logic when the change color of the foreground may also change the color of the background and vice versa.

With the very first version of chipmunk, we didn't have any automatic color calculations. Users could select any background color and any foreground color - total freedom (Also btw we didn't suggest any presets of colors and allow to set any color).

But in a quite short time, we've gotten a feedback from users: definition of colors takes too much efforts, because a user should care:
- the contrast between background and foreground in the scope of one filter
- the contrast between filters
- avoid using  "toxic" colors (too light, too acid etc.)

And we rework and reviewed the logic of setting colors based on next:
- user should be able very quick (one click) to select both: and background and foreground). That's why we have a preset of colors; that's why if you are selecting a background color, a foreground would be selected automatically (black or white as most neutral colors)
- but if a user switches to selecting foreground color, we cannot use any more b/w model for background (just because b/w model doesn't work for backgrounds), and background in this case calculated automatically as the most contrast color.

It was an informed decision based on the user's feedback.

I would close this issue, but please feel free to reopen it if my response doesn't meet your expectations or I didn't catch right your suggestion/issue.
