### ISSUE TITLE
Accept copy from a part of the log and paste as text in the search

### ISSUE THREAD

**Issue by cdamken** [esrlabs/chipmunk#1537]
**Prerequisites**

affected version: 2.26.3

make sure to check this before filing an issue:

- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

**Describe what you would like to have**

When I'm looking into the logs I see a text that I want to search, there is already an option to copy:

![Screenshot 2022-11-23 at 13 36 53](https://user-images.githubusercontent.com/7264495/203548607-5fee8588-71ea-4ef6-b7b7-54529510dc6a.png)

But there is no option to paste in the Search request.

**Potential Workaround**

So far I have to type the text.

**More Information**

Using Mac

**Comment by DmitryAstafyev** [comment]
Hello @cdamken , sorry for being late with the feedback. Am I right, you would like to see the option `Paste` in the context menu of search-input?

**Comment by DmitryAstafyev** [comment]
@cdamken  Does it mean that `ctrl + V` (`cmd + V`) doesn't work for you as a way to paste copied text?

**Comment by fur-gan** [comment]
The issue seems to be that the RMB doesn't create a context menu in the `search` input leave alone show the `Paste` option. This seems to be confusing as we show the `Copy` option inside the main view.

I think it'd be good if we not only provide the `Paste` option in the search input but anywhere we can type (e.g. editing filter name, filtering notifications, etc.)

**Comment by DmitryAstafyev** [comment]
related to #1575
