### ISSUE TITLE
add ADB Logcat Plugin

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#193]
ADB support should include
* selecting device
* connecting/disconnecting
* Support for filtering components
* support for formated columns
* possibility to select target process from the dropdown list
 ( after target process is selected - filter by this process )

as reference: look at functionality that is available on Android studio IDE

**Comment by lflo** [comment]
I think these are two separate tasks, so maybe even two separate plugins?
1. Add support for ADB inputs.
2. Add support for parsing/filtering the Android logcat log format (actually there are several variants, but focusing on the "default" one first is probably most useful). This would also be applicable for parsing Android logs from a file.

Concerning ADB input there are two options to get that:
a) Call the adb binary and parse its output (for device info) or read stdout (for the logs). However, that requires that the binary is on the user's PATH.
b) Directly talk to the adb server/daemon via its very simple TCP protocol (this is what the adb binary also does). This does not require having the adb binary in PATH (although it might be useful to try to auto-launch the adb server if it's not running yet), and might not be more complex than parsing the adb binary stdout output.

Also one more feature for this: when reading logs from a device, support waiting for device reconnect when it disconnects (instead of terminating the input - since the adb binary quits in this case).
