### ISSUE TITLE
filters that are not active influence coloring

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#718]
when we have multiple filters and some filter that occurs first is disabled, it's coloring is still used if a later filter matches
![image](https://user-images.githubusercontent.com/99541/76394865-7648e180-6376-11ea-9d9b-d83175e71556.png)
when the order is changed, it looks like this
![image](https://user-images.githubusercontent.com/99541/76395056-cfb11080-6376-11ea-8250-e251628a01ee.png)
this is still wrong since the filter matches still show

**Comment by DmitryAstafyev** [comment]
It isn't a bug, but expected behavior. Currently, we are applying colors of filters even filters aren't active. 
So, I suggest creating another issue (feature request) with a description of expected behavior. I think there are should be some additional "flag" like `visible/invisible` to control applying of coloring.
